;;; dpurge-ime-config.el --- IME configuration for DPurge markdown -*- lexical-binding: t; -*-

(defvar dpurge-vocabulary-language-config
  '((("ara" "arab")
     :direction right-to-left
     :fields ((phrase :input-method "dpurge-ara" :input-method-file "ara")
              (transcription :input-method "dpurge-semitic-postfix"
                             :input-method-file "semitic-postfix")
              (grammar :input-method nil)
              (translation :input-method nil)
              (notes :input-method nil)))
    (("aze" "latn")
     :direction left-to-right
     :fields ((phrase :input-method "dpurge-aze" :input-method-file "aze")
              (transcription :input-method nil)
              (grammar :input-method nil)
              (translation :input-method nil)
              (notes :input-method nil)))
    (("bul" "cyrl")
     :direction left-to-right
     :fields ((phrase :input-method "dpurge-bul" :input-method-file "bul")
              (transcription :input-method nil)
              (grammar :input-method nil)
              (translation :input-method nil)
              (notes :input-method nil)))
    (("ces" "latn")
     :direction left-to-right
     :fields ((phrase :input-method "dpurge-ces" :input-method-file "ces")
              (transcription :input-method nil)
              (grammar :input-method nil)
              (translation :input-method nil)
              (notes :input-method nil)))
    (("chu" "cyrl")
     :direction left-to-right
     :fields ((phrase :input-method "dpurge-chu" :input-method-file "chu")
              (transcription :input-method nil)
              (grammar :input-method nil)
              (translation :input-method nil)
              (notes :input-method nil)))
    (("cmn" "hans")
     :direction left-to-right
     :fields ((phrase :input-method "pyim"
                       :setup-function dpurge-vocabulary-setup-cmn-phrase)
              (transcription :input-method "dpurge-zho-pinyin"
                             :input-method-file "zho-pinyin")
              (grammar :input-method nil)
              (translation :input-method nil)
              (notes :input-method nil)))
    (("cmn" "hant")
     :direction left-to-right
     :fields ((phrase :input-method "pyim"
                       :setup-function dpurge-vocabulary-setup-cmn-phrase)
              (transcription :input-method "dpurge-zho-pinyin"
                             :input-method-file "zho-pinyin")
              (grammar :input-method nil)
              (translation :input-method nil)
              (notes :input-method nil)))
    (("cop" "copt")
     :direction left-to-right
     :fields ((phrase :input-method "dpurge-cop" :input-method-file "cop")
              (transcription :input-method nil)
              (grammar :input-method nil)
              (translation :input-method nil)
              (notes :input-method nil)))
    (("crh" "latn")
     :direction left-to-right
     :fields ((phrase :input-method "dpurge-crh" :input-method-file "crh")
              (transcription :input-method nil)
              (grammar :input-method nil)
              (translation :input-method nil)
              (notes :input-method nil)))
    (("dan" "latn")
     :direction left-to-right
     :fields ((phrase :input-method "dpurge-dan" :input-method-file "dan")
              (transcription :input-method nil)
              (grammar :input-method nil)
              (translation :input-method nil)
              (notes :input-method nil)))
    (("deu" "latn")
     :direction left-to-right
     :fields ((phrase :input-method "dpurge-deu" :input-method-file "deu")
              (transcription :input-method nil)
              (grammar :input-method nil)
              (translation :input-method nil)
              (notes :input-method nil)))
    (("ell" "grek")
     :direction left-to-right
     :fields ((phrase :input-method "dpurge-ell" :input-method-file "ell")
              (transcription :input-method nil)
              (grammar :input-method nil)
              (translation :input-method nil)
              (notes :input-method nil)))
    (("epo" "latn")
     :direction left-to-right
     :fields ((phrase :input-method "dpurge-epo" :input-method-file "epo")
              (transcription :input-method nil)
              (grammar :input-method nil)
              (translation :input-method nil)
              (notes :input-method nil)))
    (("fas" "arab")
     :direction right-to-left
     :fields ((phrase :input-method "dpurge-fas" :input-method-file "fas")
              (transcription :input-method "dpurge-semitic-postfix"
                             :input-method-file "semitic-postfix")
              (grammar :input-method nil)
              (translation :input-method nil)
              (notes :input-method nil)))
    (("fin" "latn")
     :direction left-to-right
     :fields ((phrase :input-method "dpurge-fin" :input-method-file "fin")
              (transcription :input-method nil)
              (grammar :input-method nil)
              (translation :input-method nil)
              (notes :input-method nil)))
    (("fra" "latn")
     :direction left-to-right
     :fields ((phrase :input-method "dpurge-fra" :input-method-file "fra")
              (transcription :input-method nil)
              (grammar :input-method nil)
              (translation :input-method nil)
              (notes :input-method nil)))
    (("grc" "grek")
     :direction left-to-right
     :fields ((phrase :input-method "dpurge-grc" :input-method-file "grc")
              (transcription :input-method nil)
              (grammar :input-method nil)
              (translation :input-method nil)
              (notes :input-method nil)))
    (("greek-polytonic" "grek")
     :direction left-to-right
     :fields ((phrase :input-method "dpurge-greek-polytonic"
                       :input-method-file "greek-polytonic")
              (transcription :input-method nil)
              (grammar :input-method nil)
              (translation :input-method nil)
              (notes :input-method nil)))
    (("heb" "hebr")
     :direction right-to-left
     :fields ((phrase :input-method "dpurge-heb" :input-method-file "heb")
              (transcription :input-method "dpurge-semitic-postfix"
                             :input-method-file "semitic-postfix")
              (grammar :input-method nil)
              (translation :input-method nil)
              (notes :input-method nil)))
    (("hin" "deva")
     :direction left-to-right
     :fields ((phrase :input-method "dpurge-hin" :input-method-file "hin")
              (transcription :input-method "dpurge-indic-postfix"
                             :input-method-file "indic-postfix")
              (grammar :input-method nil)
              (translation :input-method nil)
              (notes :input-method nil)))
    (("hun" "latn")
     :direction left-to-right
     :fields ((phrase :input-method "dpurge-hun" :input-method-file "hun")
              (transcription :input-method nil)
              (grammar :input-method nil)
              (translation :input-method nil)
              (notes :input-method nil)))
    (("hye" "armn")
     :direction left-to-right
     :fields ((phrase :input-method "dpurge-hye" :input-method-file "hye")
              (transcription :input-method nil)
              (grammar :input-method nil)
              (translation :input-method nil)
              (notes :input-method nil)))
    (("ita" "latn")
     :direction left-to-right
     :fields ((phrase :input-method "dpurge-ita" :input-method-file "ita")
              (transcription :input-method nil)
              (grammar :input-method nil)
              (translation :input-method nil)
              (notes :input-method nil)))
    (("jpn" "jpan")
     :direction left-to-right
     :fields ((phrase :input-method "japanese")
              (transcription :input-method nil)
              (grammar :input-method nil)
              (translation :input-method nil)
              (notes :input-method nil)))
    (("kat" "geor")
     :direction left-to-right
     :fields ((phrase :input-method "dpurge-kat" :input-method-file "kat")
              (transcription :input-method nil)
              (grammar :input-method nil)
              (translation :input-method nil)
              (notes :input-method nil)))
    (("kaz" "cyrl")
     :direction left-to-right
     :fields ((phrase :input-method "dpurge-kaz" :input-method-file "kaz")
              (transcription :input-method nil)
              (grammar :input-method nil)
              (translation :input-method nil)
              (notes :input-method nil)))
    (("kir" "cyrl")
     :direction left-to-right
     :fields ((phrase :input-method "dpurge-kir" :input-method-file "kir")
              (transcription :input-method nil)
              (grammar :input-method nil)
              (translation :input-method nil)
              (notes :input-method nil)))
    (("kor" "kore")
     :direction left-to-right
     :fields ((phrase :input-method "korean-ipa-romaja")
              (transcription :input-method nil)
              (grammar :input-method nil)
              (translation :input-method nil)
              (notes :input-method nil)))
    (("lav" "latn")
     :direction left-to-right
     :fields ((phrase :input-method "dpurge-lav" :input-method-file "lav")
              (transcription :input-method nil)
              (grammar :input-method nil)
              (translation :input-method nil)
              (notes :input-method nil)))
    (("lit" "latn")
     :direction left-to-right
     :fields ((phrase :input-method "dpurge-lit" :input-method-file "lit")
              (transcription :input-method nil)
              (grammar :input-method nil)
              (translation :input-method nil)
              (notes :input-method nil)))
    (("mnc" "mong")
     :direction left-to-right
     :fields ((phrase :input-method "dpurge-mnc" :input-method-file "mnc")
              (transcription :input-method nil)
              (grammar :input-method nil)
              (translation :input-method nil)
              (notes :input-method nil)))
    (("ron" "latn")
     :direction left-to-right
     :fields ((phrase :input-method "dpurge-ron" :input-method-file "ron")
              (transcription :input-method nil)
              (grammar :input-method nil)
              (translation :input-method nil)
              (notes :input-method nil)))
    (("rus" "cyrl")
     :direction left-to-right
     :fields ((phrase :input-method "dpurge-rus" :input-method-file "rus")
              (transcription :input-method nil)
              (grammar :input-method nil)
              (translation :input-method nil)
              (notes :input-method nil)))
    (("srp" "cyrl")
     :direction left-to-right
     :fields ((phrase :input-method "dpurge-srp" :input-method-file "srp")
              (transcription :input-method nil)
              (grammar :input-method nil)
              (translation :input-method nil)
              (notes :input-method nil)))
    (("sux" "xsux")
     :direction left-to-right
     :fields ((phrase :input-method "dpurge-sux" :input-method-file "sux")
              (transcription :input-method "dpurge-sux-transcription"
                             :input-method-file "sux-transcription")
              (grammar :input-method nil)
              (translation :input-method nil)
              (notes :input-method nil)))
    (("swe" "latn")
     :direction left-to-right
     :fields ((phrase :input-method "dpurge-swe" :input-method-file "swe")
              (transcription :input-method nil)
              (grammar :input-method nil)
              (translation :input-method nil)
              (notes :input-method nil)))
    (("tat" "cyrl")
     :direction left-to-right
     :fields ((phrase :input-method "dpurge-tat" :input-method-file "tat")
              (transcription :input-method nil)
              (grammar :input-method nil)
              (translation :input-method nil)
              (notes :input-method nil)))
    (("tgk" "cyrl")
     :direction left-to-right
     :fields ((phrase :input-method "dpurge-tgk" :input-method-file "tgk")
              (transcription :input-method nil)
              (grammar :input-method nil)
              (translation :input-method nil)
              (notes :input-method nil)))
    (("tur" "latn")
     :direction left-to-right
     :fields ((phrase :input-method "dpurge-tur" :input-method-file "tur")
              (transcription :input-method nil)
              (grammar :input-method nil)
              (translation :input-method nil)
              (notes :input-method nil)))
    (("urd" "arab")
     :direction right-to-left
     :fields ((phrase :input-method "dpurge-urd" :input-method-file "urd")
              (transcription :input-method "dpurge-indic-postfix"
                             :input-method-file "indic-postfix")
              (grammar :input-method nil)
              (translation :input-method nil)
              (notes :input-method nil)))
    (("vie" "latn")
     :direction left-to-right
     :fields ((phrase :input-method "dpurge-vie" :input-method-file "vie")
              (transcription :input-method nil)
              (grammar :input-method nil)
              (translation :input-method nil)
              (notes :input-method nil)))
    (("yid" "hebr")
     :direction right-to-left
     :fields ((phrase :input-method "dpurge-yid" :input-method-file "yid")
              (transcription :input-method nil)
              (grammar :input-method nil)
              (translation :input-method nil)
              (notes :input-method nil))))
  "Field editing configuration keyed by language and script.")

(provide 'dpurge-ime-config)
